[package]
name = "sequoia"
version = "0.1.0"
authors = ["Garrett Squire <garrettsquire@gmail.com>"]

[dependencies]
dtoa = "0.4"
itoa = "0.4"
lazy_static = "1.0"
parking_lot = "0.6"
pool = "0.1"

[dev-dependencies]
criterion = "0.2"

[[bench]]
name = "bench"
harness = false
